### ISSUE TITLE
Shuffledns doesn't do anything

### ISSUE THREAD

**Issue by gracjanj** [projectdiscovery/shuffledns#103]
### shuffledns version:
[INF] Current Version: v1.0.6

### environment
go version go1.17.8 linux/amd64
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS" 
5.13.0-35-generic
massdns 1.0.0

### Current Behavior:
When running shuffledns it hangs and doesn't do anything.

### Expected Behavior:
Do something.

### Steps To Reproduce:
1. Run shuffledns

```
$ shuffledns -v -d whatever.com -w ~/opt/wordlists/jhaddix-dns-all.txt -r tested-resolvers.txt 

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1.0.6

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
```
it just hangs at this point.

Let me know if you need any more information.

**Comment by mamaiamhacking** [comment]
Same problem here

**Comment by lam0r** [comment]
I also have the same problem on

go version go1.17.5 linux/amd64
4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
MassDNS 1.0.0

**Comment by ehsandeep** [comment]
@gracjanj thanks for reporting, this is now fixed in the latest release.
