### ISSUE TITLE
multi domain wildcard filtering 

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/shuffledns#159]
### Please describe your feature request:

I want to start using shuffledns and I think a core element it is lacking is multi domain wildcard filtering. Let's say you have a list of 10k subdomains from different root domains, it would be ideal to run:

`cat subs | shuffledns -r resolvers` 

and that shufflendns resolves all subdomains, and then does wildcard filtering subdomain by domain.

### Describe the use case of this feature:

Similar to what 'puredns' does, it resolves any list given, and then checks for all wildcards. As it is right now, you would have to loop over every single different root domain, which makes it a bit useless as it wastes so much time like that.

**Comment by Mzack9999** [comment]
Tasks:
- [ ] Improve wildcard filtering performance
- [ ] Implement any missing functionality available in other similar engines such as puredns
