### ISSUE TITLE
Wildcards are not removed

### ISSUE THREAD

**Issue by aishukc** [projectdiscovery/shuffledns#23]
Wildcards are not detected for some domains like internet.org .

Command that I used : 
`echo "internet.org" | shuffledns -w wordlist -r /tmp/resolver -o /tmp/internet.org -t 500`

**Comment by aishukc** [comment]
And it also takes extremely large time at `[INF] Parsing output and removing wildcards` .

It takes around an hour for list of 10K wordlist. For reference, it only takes few minutes with same wordlist for other domains.

**Comment by bauthard** [comment]
Hi @aishukc, 

This is something we will update in the readme, but to detect and remove wildcard, you need to provide `-d` domain name as well as it's get used with wildcard logic. 

so the command to use will be:- 

```
echo "internet.org" | shuffledns -d internet.org -w wordlist -r /tmp/resolver -o /tmp/internet.org -t 500
```

**Comment by bauthard** [comment]
Please try the above command and let me know if you still experience the same about wildcard and time issue, otherwise, let us know the target name to confirm which takes extra time for you.

**Comment by aishukc** [comment]
Hi @bauthard ,
Thanks for the response

I am still experiencing same issue for both wildcard and time. The target is `internet.org` for both issues.

**Comment by bauthard** [comment]
Hi @aishukc, 

Thank for adding more information, I can confirm and just reproduced on my side as well.

**Comment by bauthard** [comment]
Hi @aishukc, 

We have fixed this in https://github.com/projectdiscovery/shuffledns/tree/bugfix-wildcard-logic branch, we will keep it testing before pushing the code, meanwhile, can you confirm this from your side as well? 

To validate the fix, make sure you close the `bugfix-wildcard-logic ` branch and build the binary.

**Comment by aishukc** [comment]
Thanks @bauthard ,
The fix works perfectly for me.
