### ISSUE TITLE
Upstream minisign 404 error results in inability to install

### ISSUE THREAD

**Issue by TH3-F001** [projectdiscovery/shuffledns#257]
During go install on Fedora 38 I get the following error

`/home/user/go/pkg/mod/github.com/minio/selfupdate@v0.6.1-0.20230907112617-f11e74f84ca7/minisign.go:8:2: unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found`

Checked https://aead.dev/minisign and the page is indeed down. 

aead dev did make a recent release to github about a month ago so it doesnt seem like they've abandoned the project; however [this issue](https://github.com/aead/minisign/issues/26) was posted on the repo 2 weeks ago and no response as of yet

In the meantime I decided to make a fork and see if I can get go to pull the package from github instead (knowing very little about go mind you)

**Comment by dogancanbakir** [comment]
Investigating at https://github.com/projectdiscovery/subfinder/issues/1055#issuecomment-1826416837

**Comment by dogancanbakir** [comment]
Closing this. See https://github.com/projectdiscovery/subfinder/issues/1055#issuecomment-1827981373
