### ISSUE TITLE
hashmap size -s argument

### ISSUE THREAD

**Issue by jaikishantulswani** [projectdiscovery/shuffledns#258]
@ehsandeep @Mzack9999 shuffledns is not accepting the custom value given through the argument -mcmd for `hashmap` argument of massdns like if we try to give -mcmd `-s 35`, shuffledns execute the command with default value and with provided one like -s 10000 -s 35
One more thing, is there any way to use massdns --processes argument to run parallel processes with shuffldns

**Comment by jaikishantulswani** [comment]
@dogancanbakir Thank you for looking into this, Indeed it throws error when we supply `-mcmd -s 0` but when you try to resolve a real list and supply -mcmd -s 50 and monitor the massdns command running behind the wrapper it is executing a command like `-s 10000 -s 50`

**Comment by dogancanbakir** [comment]
After reviewing the issue again, I believe that the reason behind it is https://github.com/projectdiscovery/shuffledns/blob/db34c6634ca891f7a7df9fe75488373212a0130a/pkg/massdns/process.go#L93
If you want to modify the `-s` option, try setting `-t` instead. For instance:

```console
go run . -d example.com -list example-subdomains.txt -r resolvers.txt -t 35
```

Let me know if you have any questions!

**Comment by jaikishantulswani** [comment]
@dogancanbakir but this does't help to solve my issue as I want to control the concurrent looks which is available through -s flag `--hashmap-size`

**Comment by dogancanbakir** [comment]
shuffledns' `-t` flag controls the massdns' `-s` flag. It seems like this is exactly what you're looking for 👀

**Comment by jaikishantulswani** [comment]
@dogancanbakir Thank you, it works.One more thing, is there any workaround to use massdns -processes flag in shuffledns

**Comment by dogancanbakir** [comment]
You can use `-mcmd '--processes 2'`.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if you have any other questions.
