### ISSUE TITLE
Add Found Result Count for Resolved Subdomains on shuffledns

### ISSUE THREAD

**Issue by borhanDZ** [projectdiscovery/shuffledns#296]
I would like to suggest an enhancement to **shuffledns** that would include a feature to count the number of resolved subdomains. This addition would be particularly useful for comparing the results of **shuffledns** with **cdncheck** or similar **tools**.

![shuffledns](https://github.com/projectdiscovery/shuffledns/assets/48858118/84a8a78e-d44b-49a7-b56b-7bae503d668c)

Currently, when using **shuffledns**, it provides a list of resolved subdomains, but it doesn't offer a count of these resolved subdomains. Having this count readily available would streamline the process of comparing results from **shuffledns** with other tools like **cdncheck**.

![cdncheck](https://github.com/projectdiscovery/shuffledns/assets/48858118/91e5607d-3d4f-40fe-a2f4-a72884b13c18)

At times, I find myself staring at my computer screen, with multiple terminal windows open. I wonder if I can determine the number of subdomains hidden behind **CDNs/WAFs/cloud** services simply by analyzing the results
Thank you for considering this feature request and much love to @projectdiscovery.

**Comment by GeorginaReeder** [comment]
Thanks so much for your suggestion @borhanDZ , we'll take a look into this!
