### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cYph3r1337** [projectdiscovery/shuffledns#30]
Is there a way to print data with tag live/no rather than just giving live hosts
For ex - (like this)
google.com **live**
pikachu.google.com **not live**
corp.google.com **live**

(instead of this)
google.com
corp.google.com

**Comment by bauthard** [comment]
Hi @cYph3r1337, 

Thanks for creating this issue, I see what you mean, and to achieve the expected result we can utilize the stdout feature of the output and pass the output to dedicated tools doing the above task. 

For example, you can pipe the result to httprob or naabu which looks for port 80 or 443 and it will display only live website, closing this out as this is out of scope within the feature set of `shuffledns` 

For example:- 

```
subfinder -d example.com | shuffledns -d example.com -r resolvers.txt | naabu -silent -ports 80,443
