### ISSUE TITLE
module github.com/mholt/archiver@latest found (v3.1.1+incompatible), but does not contain package github.com/mholt/archiver

### ISSUE THREAD

**Issue by 0backtry** [projectdiscovery/shuffledns#303]
This issue actually occurred during shuffledns installation. Everything was going just find till the error happened.

user@kali:~/dir/dir> go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
go: downloading github.com/projectdiscovery/shuffledns v1.0.9
go: downloading github.com/projectdiscovery/gologger v1.1.9
go: downloading github.com/projectdiscovery/goflags v0.1.8
go: downloading github.com/projectdiscovery/utils v0.0.28
go: downloading github.com/rs/xid v1.5.0
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/remeh/sizedwaitgroup v1.0.0
go: downloading github.com/cnf/structhash v0.0.0-20201127153200-e1b16c1ebc08
go: downloading golang.org/x/exp v0.0.0-20230315142452-642cacee5cc0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/asaskevich/govalidator v0.0.0-20230301143203-a9d515a09cc2
go: downloading github.com/Masterminds/semver/v3 v3.2.1
go: downloading github.com/charmbracelet/glamour v0.6.0
go: downloading github.com/cheggaaa/pb/v3 v3.1.2
go: downloading github.com/google/go-github/v30 v30.1.0
go: downloading github.com/minio/selfupdate v0.6.0
go: downloading golang.org/x/oauth2 v0.7.0
go: downloading github.com/mholt/archiver v3.1.1+incompatible
go: downloading gopkg.in/djherbis/times.v1 v1.3.0
go: downloading github.com/miekg/dns v1.1.54
go: downloading github.com/projectdiscovery/roundrobin v0.0.6
go: downloading github.com/microcosm-cc/bluemonday v1.0.23
go: downloading github.com/saintfish/chardet v0.0.0-20230101081208-5e3ef4b5456d
go: downloading github.com/muesli/termenv v0.15.1
go: downloading github.com/yuin/goldmark v1.5.4
go: downloading github.com/yuin/goldmark-emoji v1.0.1
go: downloading github.com/VividCortex/ewma v1.2.0
go: downloading github.com/fatih/color v1.14.1
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/google/go-querystring v1.1.0
go: downloading golang.org/x/crypto v0.7.0
go: downloading aead.dev/minisign v0.2.0
go: downloading golang.org/x/net v0.9.0
go: downloading golang.org/x/sys v0.8.0
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading github.com/alecthomas/chroma v0.10.0
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/aymanbagabas/go-osc52/v2 v2.0.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/rivo/uniseg v0.4.4
go: downloading github.com/gorilla/css v1.0.0
go: downloading github.com/dlclark/regexp2 v1.8.1
go: finding module for package gopkg.in/yaml.v3
go: finding module for package github.com/mholt/archiver
go: finding module for package github.com/google/go-querystring/query
/usr/local/go/pkg/mod/github.com/projectdiscovery/gologger@v1.1.9/writer/filewithrotation.go:14:2: module github.com/mholt/archiver@latest found (v3.1.1+incompatible), but does not contain package github.com/mholt/archiver
/usr/local/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.28/file/file.go:21:2: module gopkg.in/yaml.v3@latest found (v3.0.1), but does not contain package gopkg.in/yaml.v3
/usr/local/go/pkg/mod/github.com/google/go-github/v30@v30.1.0/github/github.go:27:2: module github.com/google/

So, in attempt to fix this issue, I upgraded my "go from version go1.22.1 linux/amd64"  to "go version go1.22.2 linux/amd64".

I don't what's the root of this error.

**Comment by dogancanbakir** [comment]
Could you try running the command `go clean -modcache` and then retrying?

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issues persist.
