### ISSUE TITLE
Option to only show subdomains that do not resolve to give IPs

### ISSUE THREAD

**Issue by 0xrishabh** [projectdiscovery/shuffledns#31]
An option of taking multiple ip as input can be added to shuffedns so that if any subdomain resolves to the given IPs it will not be shown in output

## Why this feature
sometimes there are multiple A records of a non-existent domain that in return spoils the shuffldns wildcard feature.

**Comment by bauthard** [comment]
Hi @cYph3r1337. 

>  run shuffledns on *.rishabhshukla.tech and you will see that every subdomain comes as valid

This is not the case, if you run and try, you will find shuffledns eliminates them all as it handles wildcard elimination on default run.

**Comment by cYph3r1337** [comment]
Did you tried to do it, I setup the domain just for this purpose, I was not receiving filtered domains in output

**Comment by bauthard** [comment]
Yes, I got no results, assuming all are the wildcard ones, please share the valid entry if you set up any.

**Comment by cYph3r1337** [comment]
for some reason it is not working for me 
![Screenshot from 2020-05-18 15-42-25](https://user-images.githubusercontent.com/38362547/82201729-6e7d5e80-991e-11ea-8835-d0a4efc84523.png)

**Comment by bauthard** [comment]
Hey @cYph3r1337, as per the CLI interface, you are running an older version, you can use `GO111MODULE=on go get -u -v github.com/projectdiscovery/shuffledns/cmd/shuffledns` to update it, and we will update the binary to latest as well, here is the result on the latest version. 

```
root@test:~/# time shuffledns -d rishabhshukla.tech -w dns-small.txt -r resolvers-excellent.txt 

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1								

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Started generating bruteforce permutation
[INF] Generating permutations took 2.277849ms
[INF] Creating temporary massdns output file: /tmp/shuffledns296780385/br1m96m7dd9uk6pdmm1g
[INF] Executing massdns on rishabhshukla.tech
[INF] Massdns execution took 3.321617135s
[INF] Started parsing massdns output
[INF] Massdns output parsing compeleted
[INF] Started removing wildcards records
[INF] Wildcard removal completed
[INF] Finished enumeration, started writing output
[INF] Finished resolving. Hack the Planet!

real	0m12.222s
user	0m1.356s
sys	0m1.976s
root@test:~/# 
```

**Comment by bauthard** [comment]
This should be fixed with the latest update.

**Comment by mohammed-sec2010** [comment]
could you please share  resolvers-excellent.txt?
