### ISSUE TITLE
stdin is unavailable

### ISSUE THREAD

**Issue by h3zh1** [projectdiscovery/shuffledns#358]
**Describe the bug**
stdin operations according to readme.md are not available

**Shuffledns version**
v1.1.0

**Complete command you used to reproduce this**
echo projectdiscovery.io | ./shuffledns -w names.txt -r resolvers.txt -mode bruteforce

**Screenshots**
[FTL] Program exiting: domain not specified
![image](https://github.com/projectdiscovery/shuffledns/assets/68958533/961bb779-6954-4429-a59e-e11a84f715d6)

**Comment by dogancanbakir** [comment]
for ref: https://github.com/projectdiscovery/shuffledns/pull/313/commits/f131358d1cc43c0aeea73f4e9470cd0892b08552 where it got removed

**Comment by h3zh1** [comment]
THX!
So I can't hack more than one domain name in brute force mode?

**Comment by dogancanbakir** [comment]
Stdin support was removed because it didn’t add much value for most use cases and led to maintenance challenges. Instead, you can pass the domain directly as an argument:

```console
shuffledns -d projectdiscovery.io -w names.txt -r resolvers.txt -mode bruteforce
```
Thank you for understanding.
