### ISSUE TITLE
Question regarding bruteforce

### ISSUE THREAD

**Issue by yashanand** [projectdiscovery/shuffledns#38]
Is that possible to pass the known domain during Bruteforce so that it will do brute force on the know subdomains also ??

**Comment by Ice3man543** [comment]
Hi @yashanand, what do you mean? If you want to pass a domain, you can easily pass it with -d flag. Let me know if you need more help!

**Comment by yashanand** [comment]
Let's suppose I have few subdomains from the target, I want to brute force with a wordlist on all the knows subdomains. How to do that?
Using -d we can supply only one domain, is their way to supply many subdomains.??

**Comment by bauthard** [comment]
Hi @yashanand, 

I see, you are looking for recursive brute-forcing, unfortunately, shuffledns don't support that, `shuffledns` is a wrapper of massdns and limited to option available in massdns.
