### ISSUE TITLE
json output support

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/shuffledns#39]
Hello,

It would be nice to support the "json" form in the output format.

Because I often use json form in massdns.

Thanks.

**Comment by nothinux** [comment]
Hi I came to this project, when I search project with label Hacktoberfest, and i just realized that shuffledns, made by projectdiscovery like nuclei.

so i really excited to contribute. I have sent PR https://github.com/projectdiscovery/shuffledns/pull/77 for this issue.

@ehsandeep hope you can review my PR, Thank you!

**Comment by ehsandeep** [comment]
@nothinux thank you for adding this support, @gy741 this is now added into the dev version.
