### ISSUE TITLE
Help Needed for Command

### ISSUE THREAD

**Issue by attacker34** [projectdiscovery/shuffledns#4]
Hi @Ice3man543 

First of all, Thanks a lot for your hard work... This is indeed an amazing tool. Naabu Tool is also  awesome. I wanna ask about these two commands:

First Command:
```
echo hackerone.com | subfinder | shuffledns -w wordlist.txt -r resolvers.txt -silent | httprobe

```

Second Command:

```
shuffledns -d example.com -list example.com-subdomains.txt -r resolvers.txt

```

How I can Combine both Commands into one Command? Actually, in First Command I can't feed already discovered subdomains list in shuffledns.

Moreover, I wanna feed more than 1 Domains for Subdomain Enumeration. Is there any such support with this tool?

Sincerely,

**Comment by Ice3man543** [comment]
@attacker34, first of all sorry for those commands. There was a typo, we have updated the readme to reflect new changes. 

Regarding your first question, as of now it's not possible to bruteforce a domain and resolve a list of subdomains at the same time. You can run them individually for now.

Regarding multiple domains, that is also not possible as of now. But you can use a bash `while` loop to use multiple domains together. 

Thanks for the kind works!

**Comment by attacker34** [comment]
Thanks for the response.
