### ISSUE TITLE
Add generate permutations mode from subdomain list

### ISSUE THREAD

**Issue by plenumlab** [projectdiscovery/shuffledns#41]
Hello,

It would be helpful to use shuffledns to only generate permutations from previously collected subdomains

```
> cat sub-list.txt
a.new.target.com
b.old.target.com
> shuffledns -mode premute -p sub-list.txt -o output.txt
> cat output.txt
a.new.target.com
b.old.target.com
a.old.target.com
b.new.target.com
old.a.target.com
new.b.target.com
...
```

Also accepting stdin
```
> echo target.com | subfinder -silent | shuffledns -mode premute -silent
a.new.target.com
b.old.target.com
a.old.target.com
b.new.target.com
old.a.target.com
new.b.target.com
...
``` 
This would be also helpful to monitor company subdomains

**Comment by bauthard** [comment]
Hey @plenumlab, 

Thank you for suggesting this, we have `goaltdns` for this which accepts and output permutations and can be piped with other tools including shuffledns as well, I will see if we can FOSS it in the coming days, you can check the initial version at https://github.com/subfinder/goaltdns.

**Comment by plenumlab** [comment]
Hey @bauthard,

Thanks for you fast response, i just checked it and it seems like it keeps the same "structure" and adds words like the following example

```
> echo test.news.example.com | goaltdns -w words.txt | grep news.test
test.news.test.example.com
test.news.test1.example.com
test.news.testbed.example.com
test.news.testing.example.com
test.news.testing1.example.com
test.news-test.example.com
test.news-test1.example.com
test.news-testbed.example.com
test.news-testing.example.com
test.news-testing1.example.com
```
I am not sure how this can be done but doing a lot of manual inspection i usually see the following pattern on targets
owp.cust-api.dev.target.com
ows.cust-api.dev.target.com
dev.cust-apit.ows.target.com
cust-api.ows.dev.target.com

given the extremely large number of permutations it would be helpful to use this directly with shuffledns since it uses massdns to resolve domains

**Comment by bauthard** [comment]
Thanks for the feedback @plenumlab, as said in the last comment, that's the initial version of `goaltdns`, and we will FOSS current version in the coming months.

**Comment by bauthard** [comment]
Closing this as this will be implemented outside of shuffledns
