### ISSUE TITLE
issue with cron

### ISSUE THREAD

**Issue by Kiblyn11** [projectdiscovery/shuffledns#43]
Hello,

It might not be your concern but I would be really happy to have some help, if you have an idea.
First, shuffledns is really great and works very well.
That was until I try to run it with cron.
I don't know what cron is doing that could create the issue, because I'm doing really simple stuff.

**Version**: 1.0.4
**Issue**: shuffledns when running in cron task as bruteforce dns mode, is "missing"/"don't care about" the root dns (passed as -d in command) and creating permutation list without it (with only the wordlist.nothing) as like this

```
wordlist_word_1.
wordlist_word_2.
```

instead of 

```
wordlist_word_1.root.dns
wordlist_word_2.root.dns
```

It does not depend on wordlist, and the exact same command is working fine every time out of cron.
That is the crontab

```
SHELL=/bin/bash
* 07 * * * /opt/go/bin/shuffledns -d root.dns -r /path/to/resolvers.txt -w /path/to/jhaddix-dns -o /tmp/shuffledns
```

Looking into logs I cannot see any error.

```
       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Started generating bruteforce permutation
[INF] Generating permutations took 477.328179ms
[INF] Creating temporary massdns output file: /tmp/shuffledns178068042/bsudasm6sel9pe5gl2e0
[INF] Executing massdns
```

I pretty much tried everything but there must be something I don't know about go/cron which mess things up.

**Comment by Kiblyn11** [comment]
Well, just after posting I thought of something else...
Passing domain as stdin works.
I don't know if this is a bug, or if it's because cron is wrapping the command in shell, it push empty to stdin, and shuffledns forget about -d argument.

**Comment by bauthard** [comment]
Hey thanks for confirming @Kiblyn11, if it works with stdin, we can close it out, not sure what's going on with cron, and thank you for sharing the feedback.

**Comment by bauthard** [comment]
Closing as this is solved.
