### ISSUE TITLE
miss the last resolver server

### ISSUE THREAD

**Issue by okdanta** [projectdiscovery/shuffledns#44]
at file `pkg/wildcards/resolver.go`, 

```go
serverIndex := atomic.LoadInt32(&w.serversIndex)
if w.serversIndex >= int32(len(w.servers)-1) {
	atomic.StoreInt32(&w.serversIndex, 0)
	serverIndex = 0
}
resolver := w.servers[serverIndex]
```

the condition  `w.serversIndex >= int32(len(w.servers)-1) ` maybe wrong? 
because it's never use the last index of the list
it should be `w.serversIndex >= int32(len(w.servers))`

**Comment by okdanta** [comment]
i found that after change the program went wrong and i didn't know why.
so i change to 
```go
serverIndex := atomic.LoadInt32(&w.serversIndex)
resolver := w.servers[serverIndex % int32(len(w.servers))]
```

and it's work

**Comment by ehsandeep** [comment]
thank you @okdanta for reporting this, this should be fixed with https://github.com/projectdiscovery/shuffledns/pull/70
