### ISSUE TITLE
Piping or looping over domains only enumerates first in the list

### ISSUE THREAD

**Issue by breakfixrepeat** [projectdiscovery/shuffledns#49]
`cat domains.txt | shuffledns -w subs.txt -r resolvers.txt`
or
`cat domains.txt | while read line; do shuffledns -d $line -w subs.txt -r resolvers.txt -silent | anew shuffledns.txt; done`

### Expected result
shuffledns loops through each domain in domains.txt, generates permutations, brute force and produce the results for all domains.

### Actual result
shuffledns prints all domains in domains.txt and only runs permutation and brute forcing on the first domain.

**Comment by bauthard** [comment]
Hi @breakfixrepeat, 

This is expected, **shuffledns** does not support multiple domain input at once as it's just using `massdns` under the hood, I can suggest trying [interlace](https://github.com/codingo/Interlace) with shuffledns to achieve this.
