### ISSUE TITLE
Bug: ShuffleDNS hangs when trying to remove wildcards despite a domain not being given.

### ISSUE THREAD

**Issue by JeffreyShran** [projectdiscovery/shuffledns#50]
**Command:** `cat shorty.txt | shuffledns -w "commonspeak2.txt" -r "dnsvalidator/resolvers.txt" -o shuffledns.txt`

```
cat shorty.txt
001-0009302176-mc2-kreativne.atlassian.net
00333.atlassian.net
007dude.atlassian.net
007sex.atlassian.net
008-vt6kji.atlassian.net
00bc.atlassian.net
```

**Result:**
![image](https://user-images.githubusercontent.com/10995361/101181661-0f2a3600-3645-11eb-8c5e-11f5aee0628d.png)

**Suspected line number in code:** https://github.com/projectdiscovery/shuffledns/blob/ef52e064da1cdaf513ad867d462c2fc5c9a7e998/pkg/massdns/process.go#L69

shuffleDNS hangs and does nothing. Maybe I'm being impatient, I waited for an hour though? I'm unsure how to fix as the code looks sound at 1st glance. Perhaps it's my usage and I should always run with the `-d` flag?

**Comment by JeffreyShran** [comment]
It might help so I ran my command again with the `-d` and got the same behaviour. I only waited a couple of minutes this time though.

`cat shorty.txt | shuffledns -w "commonspeak2.txt" -r "dnsvalidator/resolvers.txt" -o shuffledns.txt -d atlassian.net`

If I watch it in `htop` the process barely uses any CPU/RAM as if it's stopped doing anything useful.

**Comment by bauthard** [comment]
Hi @JeffreyShran, 

Yes, to use the wildcard filter feature, you always need to use `d` flag. 

I do see the issue with the command you are running here. 

```
cat shorty.txt | shuffledns -w "commonspeak2.txt" -r "dnsvalidator/resolvers.txt" -o shuffledns.txt -d atlassian.net
```

where `shorty.txt` contains a list of subdomains, and `commonspeak2.txt` list of words to bruteforce, with shuffledns you can perform both a) bruteforce b) resolving action, but not both at same time which you doing in this case, so the right command should be:- 

Resolve + Wildcard Filter
  
```
cat shorty.txt | shuffledns -r "dnsvalidator/resolvers.txt" -o shuffledns.txt -d atlassian.net
```

Bruteforce + Wildcard Filter

```
shuffledns -r "dnsvalidator/resolvers.txt" -w "commonspeak2.txt" -o shuffledns.txt -d atlassian.net
```

**Comment by JeffreyShran** [comment]
Thanks. That makes complete sense. I thought that I could just throw it all in and it would somehow work.
