### ISSUE TITLE
Privileges could not be dropped to "nobody:nogroup"

### ISSUE THREAD

**Issue by amanpawar0602** [projectdiscovery/shuffledns#51]
![image](https://user-images.githubusercontent.com/64496315/102010631-485d5700-3d65-11eb-84e1-a318fe49956b.png)

**Comment by team-projectdiscovery** [comment]
Hi @amanpawar0602, 

As the error indicates, it's from the base tool massdns we are using in the shuffledns, so you need to ensure you are able to run massdns before running shuffledns.

Let me know if you have additional questions.

**Comment by bauthard** [comment]
Closing as this is not related to shuffledns but a local permission issue.

**Comment by icezhaoL** [comment]
how to resolve

**Comment by TheTechromancer** [comment]
Issue opened for massdns: https://github.com/blechschmidt/massdns/issues/141
