### ISSUE TITLE
Option to print ip with hostname

### ISSUE THREAD

**Issue by 0xrishabh** [projectdiscovery/shuffledns#52]
There are many time when you need IP address as well as hostname so I think it will be useful to have an option like -include-ip to print IP with the hostname 
Like this -

github.com 13.234.176.102

**Comment by team-projectdiscovery** [comment]
Thank you for the suggestion @0xrishabh, I get your point and for that we have another project named [dnsx](https://github.com/projectdiscovery/dnsx) where these use cases are supported, the purpose of this project is only to simplify the process of subdomain brute-forcing on the top of massdns, which is not maintained by us, so we have limitation and maintenance issue for adding more features on the top of it.
