### ISSUE TITLE
error installing shuffledns

### ISSUE THREAD

**Issue by 0xrishabh** [projectdiscovery/shuffledns#54]
#command:
 GO111MODULE=on go get -u -v github.com/projectdiscovery/shuffledns/cmd/shuffledns

# github.com/projectdiscovery/shuffledns/pkg/massdns
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:52:3: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:59:2: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:66:2: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:70:3: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:75:3: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:78:2: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:86:3: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:88:3: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:99:2: undefined: gologger.Infof
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:222:4: undefined: gologger.Silentf
../go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.4/pkg/massdns/process.go:222:4: too many errors

**Comment by shelld3v** [comment]
Hi, I am having the same error!

**Comment by bauthard** [comment]
@shelld3v you don't need to use `-u` flag 

```
GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns
```

**Comment by shelld3v** [comment]
No diff:

```bash
$ go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns
github.com/projectdiscovery/shuffledns/pkg/massdns
# github.com/projectdiscovery/shuffledns/pkg/massdns
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:52:3: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:59:2: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:66:2: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:70:3: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:75:3: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:78:2: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:86:3: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:88:3: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:99:2: undefined: gologger.Infof
gocode/src/github.com/projectdiscovery/shuffledns/pkg/massdns/process.go:222:4: undefined: gologger.Silentf
```

**Comment by shammarafzal** [comment]
1. sudo apt install golang
2. go install -v [github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest](http://github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest)
3. cd go/bin
4. sudo cp shuffledns /usr/bin 
5. now run shuffledns

**Comment by captain-arslan** [comment]
> 1. sudo apt install golang
> 2. go install -v [github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest](https://github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest)
> 3. cd go/bin
> 4. sudo cp shuffledns /usr/bin
> 5. now run shuffledns

thx i resolve error
