### ISSUE TITLE
False positives in version 1.0.4

### ISSUE THREAD

**Issue by sridharm17** [projectdiscovery/shuffledns#55]
I got below output when I ran with 1.0.3 and received no false positives.

shuffledns -d blusapphire.net -w /root/tools/seclists/Discovery/DNS/shubs-subdomains.txt -r resolvers.txt
[INF] Started generating bruteforce permutation
email.blusapphire.net
ti2.blusapphire.net
autodiscover.blusapphire.net
www.blusapphire.net
ftp.blusapphire.net
enterpriseregistration.blusapphire.net
prod01.blusapphire.net
products.blusapphire.net
sip.blusapphire.net
sccc.blusapphire.net

But when I ran with 1.0.4 got following output 
shuffledns -d blusapphire.net -w /root/tools/seclists/Discovery/DNS/shubs-subdomains.txt -r resolvers.txt

gamak.blusapphire.net
haik.blusapphire.net
hexcel.blusapphire.net
msoid.blusapphire.net
prod06.blusapphire.net
sccc.blusapphire.net
prod01.blusapphire.net
ftp.blusapphire.net
www.blusapphire.net
prod10.blusapphire.net
ti1.blusapphire.net
*.140-finance.blusapphire.net
*.150-finance.blusapphire.net
*.1444.blusapphire.net
*.150aniversario.blusapphire.net
*.164-finance.blusapphire.net
*.1conan.blusapphire.net
*.1800fundraiser.blusapphire.net
*.1mp30xxw.blusapphire.net
*.1.damoh.blusapphire.net
*.163-finance.blusapphire.net
*.0.pp.blusapphire.net
*.184456qipaiguanwang.blusapphire.net
*.204-finance.blusapphire.net
*.136-finance.blusapphire.net
*.134-finance.blusapphire.net
*.124-finance.blusapphire.net
*.100-finance.blusapphire.net
*.1hardware.blusapphire.net
\xc3\xb0\xc3\xbf\xc2\x90\xc5\xbe.blusapphire.net
*.0724ly.blusapphire.net
*.114.blusapphire.net
*.127-finance.blusapphire.net
*.0310fck.blusapphire.net
*.12530g.blusapphire.net
*.1iik.blusapphire.net
*.146-finance.blusapphire.net
*.15950royaloak.blusapphire.net
*.151-finance.blusapphire.net
*.195gachiga.blusapphire.net
autodiscover.blusapphire.net
docker01.blusapphire.net
devk.blusapphire.net
lyncdiscover.blusapphire.net
sip.blusapphire.net
demok.blusapphire.net
ti01.blusapphire.net
ti2.blusapphire.net
prod02.blusapphire.net
prod03.blusapphire.net
prod04.blusapphire.net

my resolvers.txt has
1.1.1.1
1.0.0.1
8.8.8.8
4.2.2.1

**Comment by bauthard** [comment]
I'm unable to reproduce this using the same setup/wordlist/resolver list @sridharm17 

```
time shuffledns -d blusapphire.net -r r.txt -w shubs-subdomains.txt

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1								

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Started generating bruteforce permutation
[INF] Generating permutations took 138.465626ms
[INF] Creating temporary massdns output file: /tmp/shuffledns599912464/c04s9um7dd9rmv8vbo90
[INF] Executing massdns on blusapphire.net
[INF] Massdns execution took 2m19.411886982s
[INF] Started parsing massdns output
[INF] Massdns output parsing compeleted
[INF] Started removing wildcards records
[INF] Wildcard removal completed
[INF] Finished enumeration, started writing output
www.blusapphire.net
ftp.blusapphire.net
autodiscover.blusapphire.net
prod01.blusapphire.net
products.blusapphire.net
[INF] Finished resolving. Hack the Planet!

real	2m19.597s
user	0m12.880s
sys	1m30.024s

root@test:~# shuffledns -version

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1								

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 1.0.4
```

**Comment by sridharm17** [comment]
Thanks for trying.
Seems like an issue with only me. I will just downgrade my version.
