### ISSUE TITLE
brute-forcing multiple domains at the same time?

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/shuffledns#56]
Hello team,

as always great tool.

I have a question about if it is possible to brute-force multiple domains at the same time?

let's say we have a list of 100 domains called `domains.txt`, is it possible to brute-force all of them with a provided wordlist?

like `cat domains.txt | shuffledns -w wordlist -r resolvers.txt` I know it is possible to do it against 1 domain like day, like `echo domain.com| etc..` but is it possible directly doing it against multiple domains at once?

Of course this can be done in a loop but just wondering if it maybe there is a flag for domains or something like that

**Comment by ehsandeep** [comment]
@marcelo321 please check this out https://github.com/projectdiscovery/shuffledns/issues/49
