### ISSUE TITLE
Add the ability to brute force subdomains of subdomains like *.corp.google.com

### ISSUE THREAD

**Issue by EthicalKid1** [projectdiscovery/shuffledns#6]
I think this would be a cool feature and would be really useful.

**Comment by Ice3man543** [comment]
@EthicalKid1, could you elaborate on the issue?

**Comment by bauthard** [comment]
If you are looking to brute force subdomain, you can do like this:- 

```
shuffledns -d corp.google.com -w wordlist.txt -r resolvers.txt
```

**Comment by EthicalKid1** [comment]
oh, thank you guys so much. @Ice3man543 @bauthard
