### ISSUE TITLE
bash: shuffledns: command not found

### ISSUE THREAD

**Issue by Deathpoolxrs** [projectdiscovery/shuffledns#65]
# GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns

# shuffledns
bash: shuffledns: command not found

**Comment by ehsandeep** [comment]
It's an issue with your go setup, you can use the following cmd to link `export PATH=$PATH:$(go env GOPATH)/bin` installed binaries.
