### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by ProgramFilesx86** [projectdiscovery/shuffledns#73]
Hello everyone,

I just followed the installation process , however the tool didn't installed,

I ran this command on kali linux 2021.2 
$ GO111MODULE=on go get -v github.com/projectdiscovery/shuffledns/cmd/shuffledns

it did downloaded as well, but when I do "shuffledns" "shuffledns.go" ...etc it returns "command not found"

I also tried to clone the repository>go get>go build 
and yet the script still not installed

Please can anyone improve the README.md about the installation and thanks in advance

**Comment by forgedhallpass** [comment]
`go get` downloads packages under `GOPATH`, or if the environmental variable is not set I believe it defaults to `$HOME/go`, hence you should be looking there. (e.g. `$GOPATH/bin/shuffledns` or `~/go/bin/shuffledns`)
