### ISSUE TITLE
Remove this sign ▶ from your installation .

### ISSUE THREAD

**Issue by AlishahMughal123** [projectdiscovery/shuffledns#87]
![image](https://user-images.githubusercontent.com/52525188/145180987-caecf078-5c6a-409c-b066-4be4a182afe7.png)

whenever you click on copy option which shows on the right side, it also copy the arrow thing so remove it so it`ll not occur an error in terminal.
as you can see here.
![image](https://user-images.githubusercontent.com/52525188/145181384-1cc10e38-7cf4-4f48-8cad-760a72ef244e.png)

I`ll do the Pull request .

thanks

**Comment by ehsandeep** [comment]
already fixed in https://github.com/projectdiscovery/shuffledns/tree/dev
