### ISSUE TITLE
Validation missing for resolver file

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/shuffledns#9]
`shuffledns` does not validate if the file input passed for the `-r` resolvers list exists on the system or not and it causes `massDNS` to fail as it can not run without resolver list, and I suspect https://github.com/projectdiscovery/shuffledns/issues/7 could be related to this. 

Example:- 

```
root@test:~# cat i_do_not_exists.txt
cat: i_do_not_exists.txt: No such file or directory
root@test:~# shuffledns -w w.txt -d test.com -r i_do_not_exists.txt

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/ v1								

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Started generating bruteforce permutation
[INF] Generating permutations took 40.776µs
[INF] Creating temporary massdns output file: /tmp/shuffledns933032530/bphtn8e7dd9sdquen18g
[INF] Executing massdns on test.com
[ERR] Could not run massdns: could not execute massdns: exit status 1
[INF] Finished resolving. Hack the Planet!
root@test:~# 
```

**Comment by Ice3man543** [comment]
Closed by #10

**Comment by munirhussain2872001** [comment]
shuffledns -r resolvers.txt -d samsung.com -w subdomains-top1million-5000.txt -o output.txt

       __        ________        __       
  ___ / /  __ __/ _/ _/ /__  ___/ /__ ___
 (_-</ _ \/ // / _/ _/ / -_)/ _  / _ \(_-<
/___/_//_/\_,_/_//_//_/\__/ \_,_/_//_/___/

                projectdiscovery.io

[INF] Current shuffledns version v1.1.0 (latest)
[FTL] Program exiting: execution mode not specified

**Comment by ypatel123456789** [comment]
@munirhussain2872001 
 
 I am facing same error. Have you resolved it ?

**Comment by shammarafzal** [comment]
> [@munirhussain2872001](https://github.com/munirhussain2872001)
> 
> I am facing same error. Have you resolved it ?

-mode bruteforce use this at the end of command

**Comment by Hammad203-code** [comment]
@shammarafzal did everything you said but now working
