### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by cyb3rsalih** [projectdiscovery/shuffledns#92]
**Describe the bug**
I am getting error when try to perform the shuffledns

**Shuffledns version**
1.0.5

**Complete command you used to reproduce this**
shuffledns -d redacted.com -list subdomains_i_found_on_redacted.txt -r ~/resolvers.txt | tee shuffle_redacted.com

**Screenshots**
Add screenshots of the error for a better context.
<img width="1069" alt="Screen Shot 2022-01-09 at 02 17 01" src="https://user-images.githubusercontent.com/17196669/148663163-009106be-72c8-43eb-85b6-430d55d25c11.png">

Maybe I misunderstand the -list argument. I've pass the subdomains I found on the `redacted.com`

If I use subdomain_keywords list for -list parameter.  There is no error and  on output as result. Just this logs.
<img width="783" alt="Screen Shot 2022-01-09 at 02 26 35" src="https://user-images.githubusercontent.com/17196669/148663432-d20e5164-09c9-48fd-bc34-8828e9071183.png">

What is the right using. Sorry I can't understand from ducumentation.

**Comment by chevonmdphillip** [comment]
I'm having the same issue: 

`panic: runtime error: index out of range [-1]

goroutine 20 [running]:
github.com/Mzack9999/roundrobin.(*RoundRobin).Next(...)
	/Users/chevonphillip/go/pkg/mod/github.com/!mzack9999/roundrobin@v0.0.0-20211019094217-f3f5553da353/roundrobin.go:62
github.com/Mzack9999/roundrobin/transport.(*RoundTransport).Next(...)
	/Users/chevonphillip/go/pkg/mod/github.com/!mzack9999/roundrobin@v0.0.0-20211019094217-f3f5553da353/transport/transport.go:30
github.com/projectdiscovery/shuffledns/pkg/wildcards.(*Resolver).LookupHost(0x140001dc200, {0x140001d6440, 0x26})
	/Users/chevonphillip/go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.5/pkg/wildcards/resolver.go:89 +0xa90
github.com/projectdiscovery/shuffledns/pkg/massdns.(*Client).filterWildcards.func1(0x140001dc400, 0x140001ec0c0, 0x140001dc360)
	/Users/chevonphillip/go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.5/pkg/massdns/process.go:158 +0xbc
created by github.com/projectdiscovery/shuffledns/pkg/massdns.(*Client).filterWildcards
	/Users/chevonphillip/go/pkg/mod/github.com/projectdiscovery/shuffledns@v1.0.5/pkg/massdns/process.go:154 +0x218`

**Comment by ehsandeep** [comment]
@cyb3rsalih @chevonmdphillip this should be fixed with latest release - https://github.com/projectdiscovery/shuffledns/releases/tag/v1.0.6
